### ISSUE TITLE
Первый день недели в календаре

### ISSUE THREAD

**Issue by parus95** [mariavlasyuk/extjs6.6-modern-locale-ru#2]
Чтобы в datefield неделя начиналась с понедельника, а не воскресенья, мне понадобилось сюда (в config Ext.locale.ru.panel.Date)

https://github.com/mariavlasyuk/extjs6.6-modern-locale-ru/blob/4ded813205c113ef1f6d74f3f4c179d2478f086d/ext-locale-ru.js#L129

добавить строку:

```
startDay: 1,
```

**Comment by mariavlasyuk** [comment]
Согласна, но лучше задать:

        Ext.Date.firstDayOfWeek = 1;
